<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NetScope.Core\NetScope.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.7" />
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.298">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\service-names-port-numbers.csv" />
    <EmbeddedResource Include="Data\nmap-services.txt" />
    <EmbeddedResource Include="Data\common-ports.zh-CN.csv" WithCulture="false" LogicalName="NetScope.Windows.Data.common-ports.zh-CN.csv" />
  </ItemGroup>

</Project>
